spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jackson:
    date-format: dd.MM.yyyy HH:mm
    time-zone: Europe/Moscow
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Настройки геокодера
geocoder:
  yandex:
    api-key: "65373eca-d019-48a8-b08b-3ab099810d22"
    url: "https://geocode-maps.yandex.ru/1.x/"
    timeout: 5000

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/musor_service}
    username: ${DB_USERNAME:musor_user}
    password: ${DB_PASSWORD:musor123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false